id: P000340
initial_creation_type: ocr
created_at: 13/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD95677
  title: སྡེ་དགེའི་བཀའ་བསྟན་དཀར་ཆག
  author: ''
  volumes:
    6931400af2e44e87a312e76979651458:
      image_group_id: I1PD95755
      title: Volume 1 of 西藏大藏经总目录 总索引
      volume_number: 1
      total_pages: 858
      base_file: v001.txt
